<a href="https://colab.research.google.com/github/Chandradithya8/Machine-Learning/blob/master/Handling_Imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("/content/creditcard.csv")
df.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0     0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62    0.0
1     0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69    0.0
2     1 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66    0.0
3     1 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50    0.0
4     2 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [ ]:
df.shape

(11959, 31)

In [ ]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
df['Class'].value_counts()

0.0    11906
1.0       52
Name: Class, dtype: int64

In [ ]:
df['Class']=df['Class'].fillna(0)
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     0
dtype: int64

In [ ]:
for i in df[['V20','V21','V22','V23','V24','V25','V26','V27','V28','Amount']]:
  df[i]=df[i].fillna(df[i].mean())
df.isnull().sum()  

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
x=df.drop('Class',axis=1)
y=df['Class']

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [ ]:
model=LogisticRegression()
grid={'C':10.0**np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,shuffle=False, random_state=None)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7)

In [ ]:
clf=GridSearchCV(model,param_grid=grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_macro', verbose=0)

In [ ]:
y_pred=clf.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred)) ## do not focus on accuracy.focus on recall and precision for an imbalanced dataset

[[3567    4]
 [   4   13]]
0.9977703455964325
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      3571
         1.0       0.76      0.76      0.76        17

    accuracy                           1.00      3588
   macro avg       0.88      0.88      0.88      3588
weighted avg       1.00      1.00      1.00      3588



In [ ]:
# descision tree is not that much affected by imbalanced dataset 
from sklearn.ensemble import RandomForestClassifier
c=RandomForestClassifier()
c.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred=c.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[3571    0]
 [   1   16]]
0.999721293199554
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      3571
         1.0       1.00      0.94      0.97        17

    accuracy                           1.00      3588
   macro avg       1.00      0.97      0.98      3588
weighted avg       1.00      1.00      1.00      3588



## Under Sampling - **reduce the points of maximum labels**
Disadvantage- loss of dataset
(Use only when the dataset is small)





In [ ]:
from collections import Counter
Counter(y_train)

Counter({0.0: 8336, 1.0: 35})

In [ ]:
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8) 
x_train_ns,y_train_ns=ns.fit_sample(x_train,y_train)
print("no of classes before fit {}".format(Counter(y_train)))
print("no of classes after fit {}".format(Counter(y_train_ns))) # 43*0.8=35

no of classes before fit Counter({0.0: 8336, 1.0: 35})
no of classes after fit Counter({0.0: 43, 1.0: 35})


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
c=RandomForestClassifier()
c.fit(x_train_ns,y_train_ns)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred=c.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred)) # gives very bad precision value

[[3556   15]
 [   0   17]]
0.995819397993311
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      3571
         1.0       0.53      1.00      0.69        17

    accuracy                           1.00      3588
   macro avg       0.77      1.00      0.85      3588
weighted avg       1.00      1.00      1.00      3588



# Over Sampling

In [ ]:
from imblearn.over_sampling import RandomOverSampler

In [ ]:
ns=RandomOverSampler(0.5) 
x_train_ns,y_train_ns=ns.fit_sample(x_train,y_train)
print("no of classes before fit {}".format(Counter(y_train)))
print("no of classes after fit {}".format(Counter(y_train_ns)))

no of classes before fit Counter({0.0: 8336, 1.0: 35})
no of classes after fit Counter({0.0: 8336, 1.0: 4168})


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
c=RandomForestClassifier()
c.fit(x_train_ns,y_train_ns)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred=c.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[3571    0]
 [   2   15]]
0.9994425863991081
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      3571
         1.0       1.00      0.88      0.94        17

    accuracy                           1.00      3588
   macro avg       1.00      0.94      0.97      3588
weighted avg       1.00      1.00      1.00      3588



# SMOTETomek

In [55]:
from imblearn.combine import SMOTETomek

In [56]:
os=SMOTETomek(0.5) 
x_train_ns,y_train_ns=os.fit_sample(x_train,y_train)
print("no of classes before fit {}".format(Counter(y_train)))
print("no of classes after fit {}".format(Counter(y_train_ns)))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


no of classes before fit Counter({0.0: 8336, 1.0: 35})
no of classes after fit Counter({0.0: 8312, 1.0: 4144})


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [57]:
from sklearn.ensemble import RandomForestClassifier
c=RandomForestClassifier()
c.fit(x_train_ns,y_train_ns)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [58]:
y_pred=c.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[3571    0]
 [   1   16]]
0.999721293199554
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      3571
         1.0       1.00      0.94      0.97        17

    accuracy                           1.00      3588
   macro avg       1.00      0.97      0.98      3588
weighted avg       1.00      1.00      1.00      3588

