<a href="https://colab.research.google.com/github/Chandradithya8/Machine-Learning/blob/master/Linear_Regression2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#LINEAR REGRESSION WITH MULTIPLE VARIABLES 
import pandas as pd
import numpy as np
from sklearn import linear_model

In [14]:
df=pd.read_csv("/homeprices1.csv.txt")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [16]:
p=df['bedrooms'].mean()
q=int(p)
q

3

In [19]:
df=df.fillna(q)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [21]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
reg.coef_ # m1 , m2 , m3

array([   137.25, -26025.  ,  -6825.  ])

In [23]:
reg.intercept_

383724.99999999994

In [25]:
reg.predict([[3000,3,15]])

array([615025.])

In [26]:
reg.predict([[2500,4,5]])

array([588625.])